services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: forex
      POSTGRES_PASSWORD: forex
      POSTGRES_DB: forexdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  pgdata: {}
